version: '3.7'
services:
    app:
      build: 
        context: ../
        dockerfile: docker/centos7.dockerfile
      container_name: dms_app
      image: dms_app
      privileged: true
      tmpfs:
        - /run
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      ports:
        - "8090:80"

volumes:
    app_data: